### ISSUE TITLE
Desktop - Conception du fichier de configuration

### ISSUE THREAD

**Issue by SantiagoChiappe** [INSQuebec/Desktop-App-Config-Entrainements#4]
**Is your feature request related to a problem? Please describe.**
Il est nécessaire de faire la conception du fichier de configuration pour définir les champs qu'il va y avoir. Ex. lien vidéo, titre, etc. Il faut aussi définir le type de fichier à implémenter (xml, JSON, etc.)

**Describe the solution you'd like**
Il y a un diagramme de classes qui montre ce que le fichier de configuration contiendra et le type de fichier dans lequel ça va être sauvegardé

**Describe alternatives you've considered**

**Additional context**
Il faut penser à l'utilisation du fichier, qu'est-ce qui est plus facile pour l'utilisation, flexibilité.

**Comment by zakdonohue** [comment]
Nous avons determiner que le meilleur format afin de preserver les données de l'utilisateur de l'app pour ensuite les réutiliser dans l'application VR est le format JSON. C'est un format qui s'integre facilement dans Unity et la lecture des config sera ainsi plus facile à déchiffrer lors des entrainements choisi par les athlètes.

En ce qui concerne la structure du fichier de configuration par entraînement, voici la structure choisie:

{ 
  trainingName: "nom de l'entrainement": String
  statistiques: {
                         withInstantFeedback: valeur du checkbox: Boolean,
                         withKPI: valeur du checkbox: Boolean,
                         withReactionTimek: valeur du checkbox: Boolean,
                         withEfficiency: valeur du checkbox: Boolean
                      }
  sequences: [
                      { videoFile: "nom du video": String,
                        timeOfOcclusion: "timeStamp": String,
                        question: "question entrée": String,
                        answers: [
                                       { id: chiffre identifiant: Int,
                                         answer: "reponse": String,
                                         weight: ponderation: Int
                                       },
                                       { id: chiffre identifiant: Int,
                                         answer: "reponse": String,
                                         weight: ponderation: Int
                                       },
                                       { id: chiffre identifiant: Int,
                                         answer: "reponse": String,
                                         weight: ponderation: Int
                                       },
                                       etc....
                                     ]
                     },
                     { videoFile: "nom du video": String,
                        timeOfOcclusion: "timeStamp": String,
                        question: "question entrée": String,
                        answers: [
                                       { id: chiffre identifiant: Int,
                                         answer: "reponse": String,
                                         weight: ponderation: Int
                                       },
                                       { id: chiffre identifiant: Int,
                                         answer: "reponse": String,
                                         weight: ponderation: Int
                                       },
                                       { id: chiffre identifiant: Int,
                                         answer: "reponse": String,
                                         weight: ponderation: Int
                                       },
                                       etc....
                                     ]
                     },
                     etc....                  
]
