### ISSUE TITLE
Desktop - Lecture du fichier de configuration

### ISSUE THREAD

**Issue by SantiagoChiappe** [INSQuebec/Desktop-App-Config-Entrainements#6]
**Is your feature request related to a problem? Please describe.**
Il est nécessaire de pouvoir lire un fichier de configuration dans l'application à partir des fichiers qui se trouvent enregistrés localement pour pouvoir faire l'édition du fichier.

**Describe the solution you'd like**
On peut lire un fichier de configuration dans l'application Desktop.

**Describe alternatives you've considered**

**Additional context**
Cette fonctionnalité pourrait être réutilisé pour la lecture des fichiers de configuration dans l'application VR

**Comment by zakdonohue** [comment]
en attente que https://github.com/INSQuebec/Desktop-App-Config-Entrainements/pull/16/files soit review et merge, mais la fonctionnalite est fini et testable a partir du click bouton modif entrainement, le fichier json selectionne sera visible en console log
